---
version: "3"
services:
 devopsdb:
   image: abbasshaik739/myreposit:dbimage
   ports:
     - "3306:3306"
   deploy:
     replicas: 3

 application:
   image: abbasshaik739/myreposit:appimage
   ports:
     - "1111:8080"
   deploy:
     replicas: 3
   depends_on:
     - "devopsdb"
